FROM node:10

WORKDIR ~/dm-platform

ADD package.json ./

RUN npm install

ADD . .

RUN npm run build

ARG DB_HOST
ENV DB_HOST=${DB_HOST}
ARG DB_NAME
ENV DB_NAME=${DB_NAME}
ARG DB_USER
ENV DB_USER=${DB_USER}
ARG DB_PASS
ENV DB_PASS=${DB_PASS}
ARG DB_PORT
ENV DB_PORT=${DB_PORT}

ARG FIREBASE_ACCOUNT_TYPE
ENV FIREBASE_ACCOUNT_TYPE=${FIREBASE_ACCOUNT_TYPE}
ARG FIREBASE_PROJECT_ID
ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
ARG FIREBASE_PRIVATE_KEY_ID
ENV FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
ARG FIREBASE_PRIVATE_KEY
ENV FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
ARG FIREBASE_CLIENT_EMAIL
ENV FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
ARG FIREBASE_CLIENT_ID
ENV FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
ARG FIREBASE_AUTH_URI
ENV FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
ARG FIREBASE_TOKEN_URI
ENV FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
ARG FIREBASE_AUTH_PROVIDER_X509_CERT_URL
ENV FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
ARG FIREBASE_CLIENT_X509_CERT_URL
ENV FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
ARG FIREBASE_DATABASE_URL
ENV FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}

ARG FIREBASE_WEB_API_KEY
ENV FIREBASE_WEB_API_KEY=${FIREBASE_WEB_API_KEY}
ARG FIREBASE_WEB_AUTH_DOMAIN
ENV FIREBASE_WEB_AUTH_DOMAIN=${FIREBASE_WEB_AUTH_DOMAIN}
ARG FIREBASE_WEB_STORAGE_BUCKET
ENV FIREBASE_WEB_STORAGE_BUCKET=${FIREBASE_WEB_STORAGE_BUCKET}
ARG FIREBASE_WEB_MESSAGING_SENDER_ID
ENV FIREBASE_WEB_MESSAGING_SENDER_ID=${FIREBASE_WEB_MESSAGING_SENDER_ID}
ARG FIREBASE_WEB_APP_ID
ENV FIREBASE_WEB_APP_ID=${FIREBASE_WEB_APP_ID}
ARG FIREBASE_WEB_MEASUREMENT_ID
ENV FIREBASE_WEB_MEASUREMENT_ID=${FIREBASE_WEB_MEASUREMENT_ID}

ARG TWILLIO_ACCOUNT_SID
ENV TWILLIO_ACCOUNT_SID=${TWILLIO_ACCOUNT_SID}
ARG TWILLIO_AUTH_TOKEN
ENV TWILLIO_AUTH_TOKEN=${TWILLIO_AUTH_TOKEN}
ARG TWILLIO_NUMBER
ENV TWILLIO_NUMBER=${TWILLIO_NUMBER}

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ARG AWS_REGION
ENV AWS_REGION=${AWS_REGION}
ARG AWS_BUCKET
ENV AWS_BUCKET=${AWS_BUCKET}

ARG SIMPLEX_API_KEY
ENV SIMPLEX_API_KEY=${SIMPLEX_API_KEY}
ARG SIMPLEX_HOST_URL
ENV SIMPLEX_HOST_URL=${SIMPLEX_HOST_URL}
ARG SIMPLEX_PARTNER_NAME
ENV SIMPLEX_PARTNER_NAME=${SIMPLEX_PARTNER_NAME}
ARG SIMPLEX_PARTNER_WEBSITE
ENV SIMPLEX_PARTNER_WEBSITE=${SIMPLEX_PARTNER_WEBSITE}

ARG SENDGRID_API_KEY
ENV SENDGRID_API_KEY=${SENDGRID_API_KEY}
ARG SENDER_EMAIL
ENV SENDER_EMAIL=${SENDER_EMAIL}
ARG SENDGRID_EMAIL_VERIFICATION_TEMPLATE_ID
ENV SENDGRID_EMAIL_VERIFICATION_TEMPLATE_ID=${SENDGRID_EMAIL_VERIFICATION_TEMPLATE_ID}
ARG SENDGRID_EMAIL_ADMIN_INVITATION_TEMPLATE_ID
ENV SENDGRID_EMAIL_ADMIN_INVITATION_TEMPLATE_ID=${SENDGRID_EMAIL_ADMIN_INVITATION_TEMPLATE_ID}
ARG SENDGRID_EMAIL_RESET_PASSWORD_TEMPLATE_ID
ENV SENDGRID_EMAIL_RESET_PASSWORD_TEMPLATE_ID=${SENDGRID_EMAIL_RESET_PASSWORD_TEMPLATE_ID}
ARG SENDGRID_EMAIL_TRANSACTION_REQUEST_TEMPLATE_ID
ENV SENDGRID_EMAIL_TRANSACTION_REQUEST_TEMPLATE_ID=${SENDGRID_EMAIL_TRANSACTION_REQUEST_TEMPLATE_ID}
ARG SENDGRID_EMAIL_TRANSACTION_APPROVE_TEMPLATE_ID
ENV SENDGRID_EMAIL_TRANSACTION_APPROVE_TEMPLATE_ID=${SENDGRID_EMAIL_TRANSACTION_APPROVE_TEMPLATE_ID}

ARG BACK_OFFICE_BASE_URL
ENV BACK_OFFICE_BASE_URL=${BACK_OFFICE_BASE_URL}

# DB migrate & seed
RUN npm run populate

EXPOSE 3000
CMD ["npm", "start"]
